---
version: "3"
services:
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=111368
      - PGID=110512
      - TZ=Etc/UTC
    volumes:
      - /mnt/syncthing:/data1
      - /home/matheus.cardoso/Documentos/backup/Docker/syncthing/config:/config
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
